### PUT atualizando informçoes do usuário

PUT http://localhost:5050/api/v1/users/userUpdate/{ID DO USUARIO PARA ATUALIZAR}
Authorization: Bearer <SEU_TOKEN_AQUI>
Content-Type: application/json

{
  "userName": "novoNomeDeUsuario123",
  "password": "senhaForteMin8Digitos",
  "email": "novo.email@exemplo.com",
  "role": "ADMIN",
  "phoneNumber": "11987654321",

  "address": {
    "houseNumber": "1500A",
    "complement": "Apto 502",
    "zipCode": "01001000",
    "street": "Rua Exemplo de Endereço",
    "bairro": "Centro",
    "city": "São Paulo",
    "state": "SP",
    "country": "Brasil"
  }
}